language: java
env:
  global:
    secure: d8h/SF0QVN0h/h5aFzPX27XfgkJXgl8ohv1K1T1ghZOzEuVneL1amczml4O6yzVWyMcsIKRj2O1UR0gstU3em4A0fKQpskPB78r4iUzWICHIkgQdW7fyIAua5PNdR/VS5feC21B9Yxf0aEFc0MvwMOiP3NNblQutMIiZVntmi7s=

install:
    - npm install

before_script: 
    - mkdir build-copy/aws-mock-copy -p
    - shopt -s extglob
    - cp ./!(build-copy) build-copy/aws-mock-copy/ -r
    - cd build-copy/aws-mock-copy
    - cd ../..
    - node example/nodejs/LocalProxy.js &

script: 
    - gradle clean coberturaCheck Javadoc check

after_success: .utility/push-to-gh-pages.sh

after_script:
    - ps axu|grep example/nodejs/LocalProxy.js|grep -v grep|awk '{print $2}'|xargs kill -9
    - cd build-copy/aws-mock-copy
    - cd ../..
    - rm -rf build-copy/aws-mock-copy

